# -*- coding: utf-8 -*-
{
    'name': "FacturaloPeru Facturación",
    'category': "web",
    'version': "19.0.1.0.0",
    'author': "FacturaloPeru",
    'website': "www.facturaloperu.com",
    'summary': "Módulo que se integra con facturación",
    'depends': [
        'l10n_pe',
        'sale_management',
        'odoope_account',
        'odoope_einvoice_base',
        'stock_picking_invoice_link',
        'odoope_product',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/api_url.xml',
        'data/account_tax.xml',
        'views/data.xml',
        'wizard/invoice_refund.xml',
        'wizard/query_status_wizard.xml',
        'reports/report.xml',
        'reports/report_a4.xml',
        'reports/report_ticket.xml',
        'views/views.xml',
        'views/res_company.xml',
        'views/product_uom.xml',
        'views/account_invoice.xml',
        'views/serie_view.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'facturaloperu_odoo_facturacion/static/src/css/api_frame.css',
            'facturaloperu_odoo_facturacion/static/src/js/main.js',
        ],
    },
    'license': 'AGPL-3',
    'auto_install': True,
    'installable': True,
    'application': True,
    "sequence": 1,
}
